name: 'Prompt Expert Bank Evaluator'
description: 'Evaluate LLM prompt changes using domain experts'
inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
  anthropic-api-key:
    description: 'Anthropic API key for Claude'
    required: true
  pr-number:
    description: 'Pull request number'
    required: true
  domain:
    description: 'Expert domain (security, performance, accuracy)'
    required: false
    default: 'security'

runs:
  using: 'node16'
  main: 'dist/action.js'