name: Auto-Evaluate PR

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'prompts/**/*.md'
      - 'prompts/**/*.txt'

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  evaluate-pr:
    uses: ./.github/workflows/evaluate-prompts.yml
    with:
      pr-number: ${{ github.event.number }}
      repository: ${{ github.repository }}
      auto-close-on-fail: true
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}