name: Claude PR Action

permissions:
  contents: write
  pull-requests: write
  issues: write

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]

jobs:
  claude-pr:
    if: contains(github.event.comment.body, '@claude')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          sparse-checkout: |
            scripts
            templates
            expert-definitions
            prompts
            package.json
          sparse-checkout-cone-mode: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd scripts
          npm install @anthropic-ai/sdk @octokit/rest

      - name: Claude PR Action
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.issue.number || github.event.pull_request.number }}
          COMMENT_BODY: ${{ github.event.comment.body }}
          IS_PR: true
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          node scripts/claude-handler.js

      - name: Create PR if needed
        if: contains(github.event.comment.body, 'create PR') || contains(github.event.comment.body, 'make changes')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Check if changes were made
          if [ -n "$(git status --porcelain)" ]; then
            BRANCH_NAME="claude-$(date +%s)"
            git checkout -b $BRANCH_NAME
            git add .
            git commit -m "Changes requested by @claude
            
            Original request: ${{ github.event.comment.body }}"
            
            git push origin $BRANCH_NAME
            
            gh pr create \
              --title "Claude Code: Automated changes" \
              --body "This PR was automatically created by Claude Code in response to: ${{ github.event.comment.body }}" \
              --base main \
              --head $BRANCH_NAME
          fi