name: PromptExpert Handler

on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  handle-promptexpert:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '@promptexpert')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ format('refs/pull/{0}/head', github.event.issue.number) }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Parse and validate command
        id: parse
        run: |
          COMMENT="${{ github.event.comment.body }}"
          echo "Parsing command: $COMMENT"
          
          # Extract domain and suggestion using grep
          if echo "$COMMENT" | grep -qE '@promptexpert\s+\w+\s+--suggest:"[^"]+"'; then
            DOMAIN=$(echo "$COMMENT" | grep -oE '@promptexpert\s+(\w+)' | awk '{print $2}')
            SUGGESTION=$(echo "$COMMENT" | grep -oE '--suggest:"([^"]+)"' | sed 's/--suggest:"//' | sed 's/"$//')
            
            echo "domain=$DOMAIN" >> $GITHUB_OUTPUT
            echo "suggestion=$SUGGESTION" >> $GITHUB_OUTPUT
            echo "valid=true" >> $GITHUB_OUTPUT
            
            echo "Parsed successfully:"
            echo "  Domain: $DOMAIN"
            echo "  Suggestion: $SUGGESTION"
          else
            echo "valid=false" >> $GITHUB_OUTPUT
            echo "Invalid command format"
          fi
          
      - name: Post error if invalid
        if: steps.parse.outputs.valid != 'true'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ Invalid command format. Use: `@promptexpert <domain> --suggest:"your suggestion"`'
            })
            
      - name: Install dependencies
        if: steps.parse.outputs.valid == 'true'
        run: |
          npm init -y
          npm install @anthropic-ai/sdk@0.24.0 @octokit/rest@19.0.0
          
      - name: Process valid command
        if: steps.parse.outputs.valid == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          DOMAIN: ${{ steps.parse.outputs.domain }}
          SUGGESTION: ${{ steps.parse.outputs.suggestion }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          COMMENT_AUTHOR: ${{ github.event.comment.user.login }}
        run: |
          node .github/scripts/process-promptexpert.js